[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["*/venv/*", "*/node_modules/*", "*/__pycache__/*", "*/\\.*/*"]

[tool.isort.sections]
FUTURE = "FUTURE"
STDLIB = "STDLIB"
THIRDPARTY = "THIRDPARTY"
FIRSTPARTY = "FIRSTPARTY"
LOCALFOLDER = "LOCALFOLDER"

[tool.isort.known_first_party]
yt_page_builder = "yt_page_builder"
audio_to_json = "audio_to_json"

[tool.isort.known_third_party]
torch = "torch"
transformers = "transformers"
librosa = "librosa"
numpy = "numpy"
accelerate = "accelerate"
yt_dlp = "yt_dlp"
spacy = "spacy"
openai = "openai"
requests = "requests"
