name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip install -r yt-page-builder/requirements.txt
        pip install -r audio-to-json/requirements.txt

    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run quick tests
      run: |
        python run_tests.py quick

    - name: Run all tests
      run: |
        python run_tests.py all

    - name: Run with pytest
      run: |
        pytest tests/ -v --cov=yt-page-builder --cov=audio-to-json --cov-report=html --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./htmlcov/index.html
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
